// Lista completa de municipios de Colombia (1122+)
const MunicipiosColombia = [
    "Abejorral, Antioquia",
    "Abriaquí, Antioquia",
    "Acacías, Meta",
    "Acandí, Chocó",
    "Acevedo, Huila",
    "Achí, Bolívar",
    "Agrado, Huila",
    "Agua de Dios, Cundinamarca",
    "Aguachica, Cesar",
    "Aguada, Santander",
    "Aguadas, Caldas",
    "Aguazul, Casanare",
    "Agustín Codazzi, Cesar",
    "Aipe, Huila",
    "Albania, Caquetá",
    "Albania, La Guajira",
    "Albania, Santander",
    "Albán, Cundinamarca",
    "Alcalá, Valle del Cauca",
    "Aldana, Nariño",
    "Alejandría, Antioquia",
    "Algarrobo, Magdalena",
    "Algeciras, Huila",
    "Almaguer, Cauca",
    "Almeida, Boyacá",
    "Alpujarra, Tolima",
    "Altamira, Huila",
    "Alto Baudó, Chocó",
    "Altos del Rosario, Bolívar",
    "Alvarado, Tolima",
    "Amagá, Antioquia",
    "Amalfi, Antioquia",
    "Ambalema, Tolima",
    "Anapoima, Cundinamarca",
    "Ancuyá, Nariño",
    "Andalucía, Valle del Cauca",
    "Andes, Antioquia",
    "Angelópolis, Antioquia",
    "Angostura, Antioquia",
    "Anolaima, Cundinamarca",
    "Anorí, Antioquia",
    "Anserma, Caldas",
    "Ansermanuevo, Valle del Cauca",
    "Anzoátegui, Tolima",
    "Anzá, Antioquia",
    "Apartadó, Antioquia",
    "Apulo, Cundinamarca",
    "Apía, Risaralda",
    "Aquitania, Boyacá",
    "Aracataca, Magdalena",
    "Aranzazu, Caldas",
    "Aratoca, Santander",
    "Arauca, Arauca",
    "Arauquita, Arauca",
    "Arbeláez, Cundinamarca",
    "Arboleda, Nariño",
    "Arboledas, Norte de Santander",
    "Arboletes, Antioquia",
    "Arcabuco, Boyacá",
    "Arenal, Bolívar",
    "Argelia, Antioquia",
    "Argelia, Cauca",
    "Argelia, Valle del Cauca",
    "Ariguaní, Magdalena",
    "Arjona, Bolívar",
    "Armenia, Antioquia",
    "Armenia, Quindío",
    "Armero, Tolima",
    "Arroyohondo, Bolívar",
    "Astrea, Cesar",
    "Ataco, Tolima",
    "Ayapel, Córdoba",
    "Bagadó, Chocó",
    "Bahía Solano, Chocó",
    "Bajo Baudó, Chocó",
    "Balboa, Cauca",
    "Balboa, Risaralda",
    "Baranoa, Atlántico",
    "Baraya, Huila",
    "Barbacoas, Nariño",
    "Barbosa, Antioquia",
    "Barbosa, Santander",
    "Barichara, Santander",
    "Barranca de Upía, Meta",
    "Barrancabermeja, Santander",
    "Barrancas, La Guajira",
    "Barranco de Loba, Bolívar",
    "Barranquilla, Atlántico",
    "Becerril, Cesar",
    "Belalcázar, Caldas",
    "Bello, Antioquia",
    "Belmira, Antioquia",
    "Beltrán, Cundinamarca",
    "Belén de Umbría, Risaralda",
    "Belén de los Andaquíes, Caquetá",
    "Belén, Boyacá",
    "Belén, Nariño",
    "Berbeo, Boyacá",
    "Betania, Antioquia",
    "Betulia, Antioquia",
    "Betulia, Santander",
    "Betéitiva, Boyacá",
    "Bituima, Cundinamarca",
    "Boavita, Boyacá",
    "Bochalema, Norte de Santander",
    "Bogotá, Cundinamarca",
    "Bojacá, Cundinamarca",
    "Bojayá, Chocó",
    "Bolívar, Cauca",
    "Bolívar, Santander",
    "Bolívar, Valle del Cauca",
    "Bosconia, Cesar",
    "Boyacá, Boyacá",
    "Brazuelo de Papayal, Bolívar",
    "Briceño, Antioquia",
    "Briceño, Boyacá",
    "Bucaramanga, Santander",
    "Bucarasica, Norte de Santander",
    "Buenaventura, Valle del Cauca",
    "Buenavista, Boyacá",
    "Buenavista, Córdoba",
    "Buenavista, Quindío",
    "Buenavista, Sucre",
    "Buenos Aires, Cauca",
    "Buesaco, Nariño",
    "Buga, Valle del Cauca",
    "Bugalagrande, Valle del Cauca",
    "Buriticá, Antioquia",
    "Busbanzá, Boyacá",
    "Cabrera, Cundinamarca",
    "Cabrera, Santander",
    "Cabuyaro, Meta",
    "Cachipay, Cundinamarca",
    "Caicedo, Antioquia",
    "Caicedonia, Valle del Cauca",
    "Caimito, Sucre",
    "Cajamarca, Tolima",
    "Cajibío, Cauca",
    "Cajicá, Cundinamarca",
    "Calamar, Bolívar",
    "Calamar, Guaviare",
    "Calarcá, Quindío",
    "Caldas, Antioquia",
    "Caldas, Boyacá",
    "Caldono, Cauca",
    "Cali, Valle del Cauca",
    "California, Santander",
    "Calima, Valle del Cauca",
    "Caloto, Cauca",
    "Campamento, Antioquia",
    "Campo de la Cruz, Atlántico",
    "Campoalegre, Huila",
    "Campohermoso, Boyacá",
    "Canalete, Córdoba",
    "Candelaria, Atlántico",
    "Candelaria, Valle del Cauca",
    "Cantagallo, Bolívar",
    "Cantón de San Pablo, Chocó",
    "Caparrapí, Cundinamarca",
    "Capitanejo, Santander",
    "Caracolí, Antioquia",
    "Caramanta, Antioquia",
    "Carcasí, Santander",
    "Carepa, Antioquia",
    "Carmen de Apicalá, Tolima",
    "Carmen de Carupa, Cundinamarca",
    "Carolina del Príncipe, Antioquia",
    "Cartagena de Indias, Bolívar",
    "Cartagena del Chairá, Caquetá",
    "Cartago, Valle del Cauca",
    "Carurú, Vaupés",
    "Casabianca, Tolima",
    "Castilla la Nueva, Meta",
    "Caucasia, Antioquia",
    "Cañasgordas, Antioquia",
    "Cepitá, Santander",
    "Cereté, Córdoba",
    "Cerinza, Boyacá",
    "Cerrito, Santander",
    "Cerro de San Antonio, Magdalena",
    "Chachagüí, Nariño",
    "Chaguaní, Cundinamarca",
    "Chalán, Sucre",
    "Chaparral, Tolima",
    "Charalá, Santander",
    "Charta, Santander",
    "Chibolo, Magdalena",
    "Chibolo, Magdalena",
    "Chigorodó, Antioquia",
    "Chima, Santander",
    "Chimichagua, Cesar",
    "Chimá, Córdoba",
    "Chinavita, Boyacá",
    "Chinchiná, Caldas",
    "Chinácota, Norte de Santander",
    "Chinú, Córdoba",
    "Chipaque, Cundinamarca",
    "Chipatá, Santander",
    "Chiquinquirá, Boyacá",
    "Chiriguaná, Cesar",
    "Chiscas, Boyacá",
    "Chita, Boyacá",
    "Chitagá, Norte de Santander",
    "Chitaraque, Boyacá",
    "Chivatá, Boyacá",
    "Chivor, Boyacá",
    "Choachí, Cundinamarca",
    "Chocontá, Cundinamarca",
    "Chámeza, Casanare",
    "Chía, Cundinamarca",
    "Chíquiza, Boyacá",
    "Cicuco, Bolívar",
    "Cimitarra, Santander",
    "Circasia, Quindío",
    "Cisneros, Antioquia",
    "Ciudad Bolívar, Antioquia",
    "Ciénaga de Oro, Córdoba",
    "Ciénaga, Magdalena",
    "Ciénega, Boyacá",
    "Clemencia, Bolívar",
    "Cocorná, Antioquia",
    "Coello, Tolima",
    "Cogua, Cundinamarca",
    "Colombia, Huila",
    "Colosó, Sucre",
    "Colón, Nariño",
    "Colón, Putumayo",
    "Concepción, Antioquia",
    "Concepción, Santander",
    "Concordia, Antioquia",
    "Concordia, Magdalena",
    "Condoto, Chocó",
    "Confines, Santander",
    "Consacá, Nariño",
    "Contadero, Nariño",
    "Contratación, Santander",
    "Convención, Norte de Santander",
    "Copacabana, Antioquia",
    "Coper, Boyacá",
    "Corinto, Cauca",
    "Coromoro, Santander",
    "Corozal, Sucre",
    "Corrales, Boyacá",
    "Cota, Cundinamarca",
    "Cotorra, Córdoba",
    "Covarachía, Boyacá",
    "Coveñas, Sucre",
    "Coyaima, Tolima",
    "Cravo Norte, Arauca",
    "Cuaspud, Nariño",
    "Cubarral, Meta",
    "Cubará, Boyacá",
    "Cucaita, Boyacá",
    "Cucunubá, Cundinamarca",
    "Cucutilla, Norte de Santander",
    "Cumaral, Meta",
    "Cumaribo, Vichada",
    "Cumbal, Nariño",
    "Cumbitara, Nariño",
    "Cunday, Tolima",
    "Curillo, Caquetá",
    "Curití, Santander",
    "Curumaní, Cesar",
    "Cuítiva, Boyacá",
    "Cáceres, Antioquia",
    "Cáchira, Norte de Santander",
    "Cácota, Norte de Santander",
    "Cáqueza, Cundinamarca",
    "Cértegui, Chocó",
    "Cómbita, Boyacá",
    "Córdoba, Bolívar",
    "Córdoba, Nariño",
    "Córdoba, Quindío",
    "Cúcuta, Norte de Santander",
    "Dabeiba, Antioquia",
    "Dagua, Valle del Cauca",
    "Dibulla, La Guajira",
    "Distracción, La Guajira",
    "Dolores, Tolima",
    "Donmatías, Antioquia",
    "Dosquebradas, Risaralda",
    "Duitama, Boyacá",
    "Duranía, Norte de Santander",
    "Ebéjico, Antioquia",
    "El Atrato, Chocó",
    "El Bagre, Antioquia",
    "El Banco, Magdalena",
    "El Cairo, Valle del Cauca",
    "El Calvario, Meta",
    "El Carmen de Atrato, Chocó",
    "El Carmen de Bolívar, Bolívar",
    "El Carmen de Chucurí, Santander",
    "El Carmen de Viboral, Antioquia",
    "El Carmen del Darién, Chocó",
    "El Carmen, Norte de Santander",
    "El Castillo, Meta",
    "El Cerrito, Valle del Cauca",
    "El Charco, Nariño",
    "El Cocuy, Boyacá",
    "El Colegio, Cundinamarca",
    "El Copey, Cesar",
    "El Doncello, Caquetá",
    "El Dorado, Meta",
    "El Dovio, Valle del Cauca",
    "El Espinal, Tolima",
    "El Espino, Boyacá",
    "El Guacamayo, Santander",
    "El Guamo, Bolívar",
    "El Molino, La Guajira",
    "El Paso, Cesar",
    "El Paujil, Caquetá",
    "El Peñol, Antioquia",
    "El Peñol, Nariño",
    "El Peñón, Bolívar",
    "El Peñón, Cundinamarca",
    "El Peñón, Santander",
    "El Pital, Huila",
    "El Piñón, Magdalena",
    "El Playón, Santander",
    "El Retiro, Antioquia",
    "El Retorno, Guaviare",
    "El Retén, Magdalena",
    "El Roble, Sucre",
    "El Rosal, Cundinamarca",
    "El Rosario, Nariño",
    "El Santuario, Antioquia",
    "El Socorro, Santander",
    "El Tablón, Nariño",
    "El Tambo, Cauca",
    "El Tambo, Nariño",
    "El Tarra, Norte de Santander",
    "El Zulia, Norte de Santander",
    "El Águila, Valle del Cauca",
    "Elías, Huila",
    "Encino, Santander",
    "Enciso, Santander",
    "Entrerríos, Antioquia",
    "Envigado, Antioquia",
    "Facatativá, Cundinamarca",
    "Falán, Tolima",
    "Filadelfia, Caldas",
    "Filandia, Quindío",
    "Firavitoba, Boyacá",
    "Flandes, Tolima",
    "Florencia, Caquetá",
    "Florencia, Cauca",
    "Floresta, Boyacá",
    "Florida, Valle del Cauca",
    "Floridablanca, Santander",
    "Florián, Santander",
    "Fonseca, La Guajira",
    "Fortul, Arauca",
    "Fosca, Cundinamarca",
    "Francisco Pizarro, Nariño",
    "Fredonia, Antioquia",
    "Fresno, Tolima",
    "Frontino, Antioquia",
    "Fuente de Oro, Meta",
    "Fundación, Magdalena",
    "Funes, Nariño",
    "Funza, Cundinamarca",
    "Fusagasugá, Cundinamarca",
    "Fómeque, Cundinamarca",
    "Fúquene, Cundinamarca",
    "Gachalá, Cundinamarca",
    "Gachancipá, Cundinamarca",
    "Gachantivá, Boyacá",
    "Gachetá, Cundinamarca",
    "Galapa, Atlántico",
    "Galeras, Sucre",
    "Galán, Santander",
    "Gama, Cundinamarca",
    "Gamarra, Cesar",
    "Garagoa, Boyacá",
    "Garzón, Huila",
    "Gigante, Huila",
    "Ginebra, Valle del Cauca",
    "Giraldo, Antioquia",
    "Girardot, Cundinamarca",
    "Girardota, Antioquia",
    "Girón, Santander",
    "González, Cesar",
    "Gramalote, Norte de Santander",
    "Granada, Antioquia",
    "Granada, Cundinamarca",
    "Granada, Meta",
    "Guaca, Santander",
    "Guacamayas, Boyacá",
    "Guacarí, Valle del Cauca",
    "Guachené, Cauca",
    "Guachetá, Cundinamarca",
    "Guachucal, Nariño",
    "Guadalupe, Antioquia",
    "Guadalupe, Huila",
    "Guadalupe, Santander",
    "Guaduas, Cundinamarca",
    "Guaitarilla, Nariño",
    "Gualmatán, Nariño",
    "Guamal, Magdalena",
    "Guamal, Meta",
    "Guamo, Tolima",
    "Guapotá, Santander",
    "Guapí, Cauca",
    "Guaranda, Sucre",
    "Guarne, Antioquia",
    "Guasca, Cundinamarca",
    "Guatapé, Antioquia",
    "Guataquí, Cundinamarca",
    "Guatavita, Cundinamarca",
    "Guateque, Boyacá",
    "Guavatá, Santander",
    "Guayabal de Síquima, Cundinamarca",
    "Guayabetal, Cundinamarca",
    "Guayatá, Boyacá",
    "Gutiérrez, Cundinamarca",
    "Guática, Risaralda",
    "Gámbita, Santander",
    "Gámeza, Boyacá",
    "Génova, Quindío",
    "Gómez Plata, Antioquia",
    "Güepsa, Santander",
    "Güicán, Boyacá",
    "Hacarí, Norte de Santander",
    "Hatillo de Loba, Bolívar",
    "Hato Corozal, Casanare",
    "Hato, Santander",
    "Hatonuevo, La Guajira",
    "Heliconia, Antioquia",
    "Herrán, Norte de Santander",
    "Herveo, Tolima",
    "Hispania, Antioquia",
    "Hobo, Huila",
    "Honda, Tolima",
    "Ibagué, Tolima",
    "Icononzo, Tolima",
    "Iles, Nariño",
    "Imués, Nariño",
    "Inzá, Cauca",
    "Inírida, Guainía",
    "Ipiales, Nariño",
    "Isnos, Huila",
    "Istmina, Chocó",
    "Itagüí, Antioquia",
    "Ituango, Antioquia",
    "Iza, Boyacá",
    "Jambaló, Cauca",
    "Jamundí, Valle del Cauca",
    "Jardín, Antioquia",
    "Jenesano, Boyacá",
    "Jericó, Antioquia",
    "Jericó, Boyacá",
    "Jerusalén, Cundinamarca",
    "Jesús María, Santander",
    "Jordán, Santander",
    "Juan de Acosta, Atlántico",
    "Junín, Cundinamarca",
    "Juradó, Chocó",
    "La Apartada, Córdoba",
    "La Argentina, Huila",
    "La Belleza, Santander",
    "La Calera, Cundinamarca",
    "La Capilla, Boyacá",
    "La Ceja, Antioquia",
    "La Celia, Risaralda",
    "La Cruz, Nariño",
    "La Cumbre, Valle del Cauca",
    "La Dorada, Caldas",
    "La Esperanza, Norte de Santander",
    "La Estrella, Antioquia",
    "La Florida, Nariño",
    "La Gloria (Cesar), Cesar",
    "La Jagua de Ibirico, Cesar",
    "La Jagua del Pilar, La Guajira",
    "La Llanada, Nariño",
    "La Macarena, Meta",
    "La Merced, Caldas",
    "La Mesa, Cundinamarca",
    "La Montañita, Caquetá",
    "La Palma, Cundinamarca",
    "La Paz, Cesar",
    "La Paz, Santander",
    "La Peña, Cundinamarca",
    "La Pintada, Antioquia",
    "La Plata, Huila",
    "La Playa de Belén, Norte de Santander",
    "La Primavera, Vichada",
    "La Salina, Casanare",
    "La Sierra, Cauca",
    "La Tebaida, Quindío",
    "La Tola, Nariño",
    "La Unión, Antioquia",
    "La Unión, Nariño",
    "La Unión, Sucre",
    "La Unión, Valle del Cauca",
    "La Uribe, Meta",
    "La Uvita, Boyacá",
    "La Vega, Cauca",
    "La Vega, Cundinamarca",
    "La Victoria, Boyacá",
    "La Victoria, Valle del Cauca",
    "La Virginia, Risaralda",
    "Labateca, Norte de Santander",
    "Labranzagrande, Boyacá",
    "Landázuri, Santander",
    "Lebrija, Santander",
    "Leiva, Nariño",
    "Lejanías, Meta",
    "Lenguazaque, Cundinamarca",
    "Leticia, Amazonas",
    "Liborina, Antioquia",
    "Linares, Nariño",
    "Litoral de San Juan, Chocó",
    "Lloró, Chocó",
    "Lorica, Córdoba",
    "Los Andes, Nariño",
    "Los Córdobas, Córdoba",
    "Los Palmitos, Sucre",
    "Los Patios, Norte de Santander",
    "Los Santos, Santander",
    "Lourdes, Norte de Santander",
    "Luruaco, Atlántico",
    "Lérida, Tolima",
    "Líbano, Tolima",
    "López de Micay, Cauca",
    "Macanal, Boyacá",
    "Macaravita, Santander",
    "Maceo, Antioquia",
    "Machetá, Cundinamarca",
    "Madrid, Cundinamarca",
    "Magangué, Bolívar",
    "Magüí Payán, Nariño",
    "Mahates, Bolívar",
    "Maicao, La Guajira",
    "Majagual, Sucre",
    "Malambo, Atlántico",
    "Mallama, Nariño",
    "Manatí, Atlántico",
    "Manaure Balcón del Cesar, Cesar",
    "Manaure, La Guajira",
    "Manizales, Caldas",
    "Manta, Cundinamarca",
    "Manzanares, Caldas",
    "Maní, Casanare",
    "Mapiripán, Meta",
    "Margarita, Bolívar",
    "Marinilla, Antioquia",
    "Maripí, Boyacá",
    "Mariquita, Tolima",
    "Marmato, Caldas",
    "Marquetalia, Caldas",
    "Marsella, Risaralda",
    "Marulanda, Caldas",
    "María la Baja, Bolívar",
    "Matanza, Santander",
    "Medellín, Antioquia",
    "Medina, Cundinamarca",
    "Medio Atrato, Chocó",
    "Medio Baudó, Chocó",
    "Medio San Juan, Chocó",
    "Melgar, Tolima",
    "Mercaderes, Cauca",
    "Mesetas, Meta",
    "Milán, Caquetá",
    "Miraflores, Boyacá",
    "Miraflores, Guaviare",
    "Miranda, Cauca",
    "Mistrató, Risaralda",
    "Mitú, Vaupés",
    "Mocoa, Putumayo",
    "Mogotes, Santander",
    "Molagavita, Santander",
    "Momil, Córdoba",
    "Mompós, Bolívar",
    "Mongua, Boyacá",
    "Monguí, Boyacá",
    "Moniquirá, Boyacá",
    "Montebello, Antioquia",
    "Montecristo, Bolívar",
    "Montelíbano, Córdoba",
    "Montenegro, Quindío",
    "Monterrey, Casanare",
    "Montería, Córdoba",
    "Morales, Bolívar",
    "Morales, Cauca",
    "Morelia, Caquetá",
    "Morroa, Sucre",
    "Mosquera, Cundinamarca",
    "Mosquera, Nariño",
    "Motavita, Boyacá",
    "Moñitos, Córdoba",
    "Murillo, Tolima",
    "Murindó, Antioquia",
    "Mutatá, Antioquia",
    "Mutiscua, Norte de Santander",
    "Muzo, Boyacá",
    "Málaga, Santander",
    "Nariño, Antioquia",
    "Nariño, Cundinamarca",
    "Nariño, Nariño",
    "Natagaima, Tolima",
    "Nechí, Antioquia",
    "Necoclí, Antioquia",
    "Neira, Caldas",
    "Neiva, Huila",
    "Nemocón, Cundinamarca",
    "Nilo, Cundinamarca",
    "Nimaima, Cundinamarca",
    "Nobsa, Boyacá",
    "Nocaima, Cundinamarca",
    "Norcasia, Caldas",
    "Norosí, Bolívar",
    "Nueva Granada, Magdalena",
    "Nuevo Colón, Boyacá",
    "Nunchía, Casanare",
    "Nuquí, Chocó",
    "Nátaga, Huila",
    "Nóvita, Chocó",
    "Obando, Valle del Cauca",
    "Ocamonte, Santander",
    "Ocaña, Norte de Santander",
    "Oiba, Santander",
    "Oicatá, Boyacá",
    "Olaya Herrera, Nariño",
    "Olaya, Antioquia",
    "Onzaga, Santander",
    "Oporapa, Huila",
    "Orito, Putumayo",
    "Orocué, Casanare",
    "Ortega, Tolima",
    "Ospina, Nariño",
    "Otanche, Boyacá",
    "Ovejas, Sucre",
    "Pachavita, Boyacá",
    "Pacho, Cundinamarca",
    "Padilla, Cauca",
    "Paicol, Huila",
    "Pailitas, Cesar",
    "Paime, Cundinamarca",
    "Paipa, Boyacá",
    "Pajarito, Boyacá",
    "Palermo, Huila",
    "Palestina, Caldas",
    "Palestina, Huila",
    "Palmar de Varela, Atlántico",
    "Palmar, Santander",
    "Palmas del Socorro, Santander",
    "Palmira, Valle del Cauca",
    "Palocabildo, Tolima",
    "Pamplona, Norte de Santander",
    "Pamplonita, Norte de Santander",
    "Pandi, Cundinamarca",
    "Panqueba, Boyacá",
    "Paratebueno, Cundinamarca",
    "Pasca, Cundinamarca",
    "Pasto, Nariño",
    "Patía, Cauca",
    "Pauna, Boyacá",
    "Paya, Boyacá",
    "Paz de Ariporo, Casanare",
    "Paz del Río, Boyacá",
    "Pedraza, Magdalena",
    "Pelaya, Cesar",
    "Pensilvania, Caldas",
    "Peque, Antioquia",
    "Pereira, Risaralda",
    "Pesca, Boyacá",
    "Piamonte, Cauca",
    "Piedecuesta, Santander",
    "Piedras, Tolima",
    "Piendamó, Cauca",
    "Pijao, Quindío",
    "Pijiño del Carmen, Magdalena",
    "Pinchote, Santander",
    "Pinillos, Bolívar",
    "Piojó, Atlántico",
    "Pisba, Boyacá",
    "Pitalito, Huila",
    "Pivijay, Magdalena",
    "Planadas, Tolima",
    "Planeta Rica, Córdoba",
    "Plato, Magdalena",
    "Policarpa, Nariño",
    "Polonuevo, Atlántico",
    "Ponedera, Atlántico",
    "Popayán, Cauca",
    "Pore, Casanare",
    "Potosí, Nariño",
    "Pradera, Valle del Cauca",
    "Prado, Tolima",
    "Providencia y Santa Catalina Islas, San Andrés y Providencia",
    "Providencia, Nariño",
    "Pueblo Bello, Cesar",
    "Pueblo Nuevo, Córdoba",
    "Pueblo Rico, Risaralda",
    "Pueblo Viejo, Magdalena",
    "Pueblorrico, Antioquia",
    "Puente Nacional, Santander",
    "Puerres, Nariño",
    "Puerto Asís, Putumayo",
    "Puerto Berrío, Antioquia",
    "Puerto Boyacá, Boyacá",
    "Puerto Caicedo, Putumayo",
    "Puerto Carreño, Vichada",
    "Puerto Colombia, Atlántico",
    "Puerto Concordia, Meta",
    "Puerto Escondido, Córdoba",
    "Puerto Gaitán, Meta",
    "Puerto Guzmán, Putumayo",
    "Puerto Leguízamo, Putumayo",
    "Puerto Libertador, Córdoba",
    "Puerto Lleras, Meta",
    "Puerto López, Meta",
    "Puerto Nare, Antioquia",
    "Puerto Nariño, Amazonas",
    "Puerto Parra, Santander",
    "Puerto Rico, Caquetá",
    "Puerto Rico, Meta",
    "Puerto Rondón, Arauca",
    "Puerto Salgar, Cundinamarca",
    "Puerto Santander, Norte de Santander",
    "Puerto Tejada, Cauca",
    "Puerto Triunfo, Antioquia",
    "Puerto Wilches, Santander",
    "Pulí, Cundinamarca",
    "Pupiales, Nariño",
    "Puracé, Cauca",
    "Purificación, Tolima",
    "Purísima, Córdoba",
    "Pácora, Caldas",
    "Páez, Boyacá",
    "Páez, Cauca",
    "Páramo, Santander",
    "Quebradanegra, Cundinamarca",
    "Quetame, Cundinamarca",
    "Quibdó, Chocó",
    "Quimbaya, Quindío",
    "Quinchía, Risaralda",
    "Quipile, Cundinamarca",
    "Quípama, Boyacá",
    "Ragonvalia, Norte de Santander",
    "Ramiriquí, Boyacá",
    "Recetor, Casanare",
    "Regidor, Bolívar",
    "Remedios, Antioquia",
    "Remolino, Magdalena",
    "Repelón, Atlántico",
    "Restrepo, Meta",
    "Restrepo, Valle del Cauca",
    "Ricaurte, Cundinamarca",
    "Ricaurte, Nariño",
    "Rioblanco, Tolima",
    "Riofrío, Valle del Cauca",
    "Riohacha, La Guajira",
    "Rionegro, Antioquia",
    "Rionegro, Santander",
    "Riosucio, Caldas",
    "Riosucio, Chocó",
    "Risaralda, Caldas",
    "Rivera, Huila",
    "Roberto Payán, Nariño",
    "Roldanillo, Valle del Cauca",
    "Roncesvalles, Tolima",
    "Rondón, Boyacá",
    "Rosas, Cauca",
    "Rovira, Tolima",
    "Ráquira, Boyacá",
    "Río Iró, Chocó",
    "Río Quito, Chocó",
    "Río Viejo, Bolívar",
    "Río de Oro, Cesar",
    "Sabana de Torres, Santander",
    "Sabanagrande, Atlántico",
    "Sabanalarga, Antioquia",
    "Sabanalarga, Atlántico",
    "Sabanalarga, Casanare",
    "Sabanas de San Ángel, Magdalena",
    "Sabaneta, Antioquia",
    "Saboyá, Boyacá",
    "Sahagún, Córdoba",
    "Saladoblanco, Huila",
    "Salamina, Caldas",
    "Salamina, Magdalena",
    "Salazar de Las Palmas, Norte de Santander",
    "Saldaña, Tolima",
    "Salento, Quindío",
    "Salgar, Antioquia",
    "Samacá, Boyacá",
    "Samaniego, Nariño",
    "Samaná, Caldas",
    "Sampués, Sucre",
    "San Agustín, Huila",
    "San Alberto, Cesar",
    "San Andrés de Cuerquia, Antioquia",
    "San Andrés de Sotavento, Córdoba",
    "San Andrés, San Andrés y Providencia",
    "San Andrés, Santander",
    "San Antero, Córdoba",
    "San Antonio de Palmito, Sucre",
    "San Antonio del Tequendama, Cundinamarca",
    "San Antonio, Tolima",
    "San Benito Abad, Sucre",
    "San Benito, Santander",
    "San Bernardo del Viento, Córdoba",
    "San Bernardo, Cundinamarca",
    "San Bernardo, Nariño",
    "San Calixto, Norte de Santander",
    "San Carlos de Guaroa, Meta",
    "San Carlos, Antioquia",
    "San Carlos, Córdoba",
    "San Cayetano, Cundinamarca",
    "San Cayetano, Norte de Santander",
    "San Cristóbal, Bolívar",
    "San Diego, Cesar",
    "San Eduardo, Boyacá",
    "San Estanislao, Bolívar",
    "San Fernando, Bolívar",
    "San Francisco, Antioquia",
    "San Francisco, Cundinamarca",
    "San Francisco, Putumayo",
    "San Gil, Santander",
    "San Jacinto del Cauca, Bolívar",
    "San Jacinto, Bolívar",
    "San Jerónimo, Antioquia",
    "San Joaquín, Santander",
    "San José de Albán, Nariño",
    "San José de Miranda, Santander",
    "San José de Pare, Boyacá",
    "San José de Uré, Córdoba",
    "San José de la Montaña, Antioquia",
    "San José del Fragua, Caquetá",
    "San José del Guaviare, Guaviare",
    "San José del Palmar, Chocó",
    "San José, Caldas",
    "San Juan Nepomuceno, Bolívar",
    "San Juan de Arama, Meta",
    "San Juan de Betulia, Sucre",
    "San Juan de Rioseco, Cundinamarca",
    "San Juan de Urabá, Antioquia",
    "San Juan del Cesar, La Guajira",
    "San Juanito, Meta",
    "San Lorenzo, Nariño",
    "San Luis de Gaceno, Boyacá",
    "San Luis de Palenque, Casanare",
    "San Luis, Antioquia",
    "San Luis, Tolima",
    "San Marcos, Sucre",
    "San Martín de Loba, Bolívar",
    "San Martín, Cesar",
    "San Martín, Meta",
    "San Mateo, Boyacá",
    "San Miguel de Sema, Boyacá",
    "San Miguel, Putumayo",
    "San Miguel, Santander",
    "San Onofre, Sucre",
    "San Pablo de Borbur, Boyacá",
    "San Pablo, Bolívar",
    "San Pablo, Nariño",
    "San Pedro de Cartago, Nariño",
    "San Pedro de Urabá, Antioquia",
    "San Pedro de los Milagros, Antioquia",
    "San Pedro, Sucre",
    "San Pedro, Valle del Cauca",
    "San Pelayo, Córdoba",
    "San Rafael, Antioquia",
    "San Roque, Antioquia",
    "San Sebastián de Buenavista, Magdalena",
    "San Sebastián, Cauca",
    "San Vicente de Chucurí, Santander",
    "San Vicente del Caguán, Caquetá",
    "San Vicente, Antioquia",
    "San Zenón, Magdalena",
    "Sandoná, Nariño",
    "Santa Ana, Magdalena",
    "Santa Bárbara de Pinto, Magdalena",
    "Santa Bárbara, Antioquia",
    "Santa Bárbara, Nariño",
    "Santa Bárbara, Santander",
    "Santa Catalina, Bolívar",
    "Santa Fe de Antioquia, Antioquia",
    "Santa Helena del Opón, Santander",
    "Santa Isabel, Tolima",
    "Santa Lucía, Atlántico",
    "Santa Marta, Magdalena",
    "Santa María, Boyacá",
    "Santa María, Huila",
    "Santa Rosa de Cabal, Risaralda",
    "Santa Rosa de Osos, Antioquia",
    "Santa Rosa de Viterbo, Boyacá",
    "Santa Rosa del Sur, Bolívar",
    "Santa Rosa, Bolívar",
    "Santa Rosa, Cauca",
    "Santa Rosalía, Vichada",
    "Santa Sofía, Boyacá",
    "Santacruz, Nariño",
    "Santana, Boyacá",
    "Santander de Quilichao, Cauca",
    "Santiago, Norte de Santander",
    "Santiago, Putumayo",
    "Santo Domingo de Silos, Norte de Santander",
    "Santo Domingo, Antioquia",
    "Santo Tomás, Atlántico",
    "Santuario, Risaralda",
    "Sapuyes, Nariño",
    "Saravena, Arauca",
    "Sardinata, Norte de Santander",
    "Sasaima, Cundinamarca",
    "Sativanorte, Boyacá",
    "Sativasur, Boyacá",
    "Segovia, Antioquia",
    "Sesquilé, Cundinamarca",
    "Sevilla, Valle del Cauca",
    "Siachoque, Boyacá",
    "Sibaté, Cundinamarca",
    "Sibundoy, Putumayo",
    "Silvania, Cundinamarca",
    "Silvia, Cauca",
    "Simacota, Santander",
    "Simijaca, Cundinamarca",
    "Simití, Bolívar",
    "Sincelejo, Sucre",
    "Sincé, Sucre",
    "Sipí, Chocó",
    "Sitionuevo, Magdalena",
    "Soacha, Cundinamarca",
    "Soatá, Boyacá",
    "Socha, Boyacá",
    "Socotá, Boyacá",
    "Sogamoso, Boyacá",
    "Solano, Caquetá",
    "Soledad, Atlántico",
    "Solita, Caquetá",
    "Somondoco, Boyacá",
    "Sonsón, Antioquia",
    "Sopetrán, Antioquia",
    "Soplaviento, Bolívar",
    "Sopó, Cundinamarca",
    "Sora, Boyacá",
    "Soracá, Boyacá",
    "Sotaquirá, Boyacá",
    "Sotará, Cauca",
    "Suaita, Santander",
    "Suaza, Huila",
    "Subachoque, Cundinamarca",
    "Sucre, Cauca",
    "Sucre, Santander",
    "Sucre, Sucre",
    "Suesca, Cundinamarca",
    "Supatá, Cundinamarca",
    "Supía, Caldas",
    "Suratá, Santander",
    "Susa, Cundinamarca",
    "Susacón, Boyacá",
    "Sutamarchán, Boyacá",
    "Sutatausa, Cundinamarca",
    "Sutatenza, Boyacá",
    "Suán, Atlántico",
    "Suárez, Cauca",
    "Suárez, Tolima",
    "Sácama, Casanare",
    "Sáchica, Boyacá",
    "Tabio, Cundinamarca",
    "Tadó, Chocó",
    "Talaigua Nuevo, Bolívar",
    "Tamalameque, Cesar",
    "Tame, Arauca",
    "Taminango, Nariño",
    "Tangua, Nariño",
    "Taraira, Vaupés",
    "Tarazá, Antioquia",
    "Tarqui, Huila",
    "Tarso, Antioquia",
    "Tasco, Boyacá",
    "Tauramena, Casanare",
    "Tausa, Cundinamarca",
    "Tello, Huila",
    "Tena, Cundinamarca",
    "Tenerife, Magdalena",
    "Tenjo, Cundinamarca",
    "Tenza, Boyacá",
    "Teorama, Norte de Santander",
    "Teruel, Huila",
    "Tesalia, Huila",
    "Tibacuy, Cundinamarca",
    "Tibaná, Boyacá",
    "Tibasosa, Boyacá",
    "Tibirita, Cundinamarca",
    "Tibú, Norte de Santander",
    "Tierralta, Córdoba",
    "Timaná, Huila",
    "Timbiquí, Cauca",
    "Timbío, Cauca",
    "Tinjacá, Boyacá",
    "Tipacoque, Boyacá",
    "Tiquisio, Bolívar",
    "Titiribí, Antioquia",
    "Toca, Boyacá",
    "Tocaima, Cundinamarca",
    "Tocancipá, Cundinamarca",
    "Togüí, Boyacá",
    "Toledo, Antioquia",
    "Toledo, Norte de Santander",
    "Tolú Viejo, Sucre",
    "Tolú, Sucre",
    "Tona, Santander",
    "Topaipí, Cundinamarca",
    "Toribío, Cauca",
    "Toro, Valle del Cauca",
    "Tota, Boyacá",
    "Totoró, Cauca",
    "Trinidad, Casanare",
    "Trujillo, Valle del Cauca",
    "Tubará, Atlántico",
    "Tuchín, Córdoba",
    "Tuluá, Valle del Cauca",
    "Tumaco, Nariño",
    "Tunja, Boyacá",
    "Tununguá, Boyacá",
    "Turbaco, Bolívar",
    "Turbaná, Bolívar",
    "Turbo, Antioquia",
    "Turmequé, Boyacá",
    "Tuta, Boyacá",
    "Tutazá, Boyacá",
    "Támara, Casanare",
    "Támesis, Antioquia",
    "Tópaga, Boyacá",
    "Túquerres, Nariño",
    "Ubalá, Cundinamarca",
    "Ubaque, Cundinamarca",
    "Ubaté, Cundinamarca",
    "Ulloa, Valle del Cauca",
    "Une, Cundinamarca",
    "Unguía, Chocó",
    "Unión Panamericana, Chocó",
    "Uramita, Antioquia",
    "Uribia, La Guajira",
    "Urrao, Antioquia",
    "Urumita, La Guajira",
    "Usiacurí, Atlántico",
    "Valdivia, Antioquia",
    "Valencia, Córdoba",
    "Valle de San José, Santander",
    "Valle de San Juan, Tolima",
    "Valle del Guamuez, Putumayo",
    "Valledupar, Cesar",
    "Valparaíso, Antioquia",
    "Valparaíso, Caquetá",
    "Vegachí, Antioquia",
    "Venadillo, Tolima",
    "Venecia, Antioquia",
    "Venecia, Cundinamarca",
    "Ventaquemada, Boyacá",
    "Vergara, Cundinamarca",
    "Versalles, Valle del Cauca",
    "Vetas, Santander",
    "Vianí, Cundinamarca",
    "Victoria, Caldas",
    "Vigía del Fuerte, Antioquia",
    "Vijes, Valle del Cauca",
    "Villa Caro, Norte de Santander",
    "Villa Rica, Cauca",
    "Villa de Leyva, Boyacá",
    "Villa del Rosario, Norte de Santander",
    "Villagarzón, Putumayo",
    "Villagómez, Cundinamarca",
    "Villahermosa, Tolima",
    "Villamaría, Caldas",
    "Villanueva, Bolívar",
    "Villanueva, Casanare",
    "Villanueva, La Guajira",
    "Villanueva, Santander",
    "Villapinzón, Cundinamarca",
    "Villarrica, Tolima",
    "Villavicencio, Meta",
    "Villavieja, Huila",
    "Villeta, Cundinamarca",
    "Viotá, Cundinamarca",
    "Viracachá, Boyacá",
    "Vista Hermosa, Meta",
    "Viterbo, Caldas",
    "Vélez, Santander",
    "Yacopí, Cundinamarca",
    "Yacuanquer, Nariño",
    "Yaguará, Huila",
    "Yalí, Antioquia",
    "Yarumal, Antioquia",
    "Yolombó, Antioquia",
    "Yondó, Antioquia",
    "Yopal, Casanare",
    "Yotoco, Valle del Cauca",
    "Yumbo, Valle del Cauca",
    "Zambrano, Bolívar",
    "Zapatoca, Santander",
    "Zapayán, Magdalena",
    "Zaragoza, Antioquia",
    "Zarzal, Valle del Cauca",
    "Zetaquira, Boyacá",
    "Zipacón, Cundinamarca",
    "Zipaquirá, Cundinamarca",
    "Zona Bananera, Magdalena",
    "Ábrego, Norte de Santander",
    "Íquira, Huila",
    "Úmbita, Boyacá",
    "Útica, Cundinamarca"
];

// Función para poblar el datalist
function poblarMunicipios() {
    const datalist = document.getElementById('municipios-colombia');
    if (!datalist) return;
    
    // Solo poblar si está vacío
    if (datalist.options.length === 0) {
        const fragment = document.createDocumentFragment();
        MunicipiosColombia.forEach(municipio => {
            const option = document.createElement('option');
            option.value = municipio;
            fragment.appendChild(option);
        });
        datalist.appendChild(fragment);
    }
}

// Ejecutar cuando el DOM esté listo
document.addEventListener('DOMContentLoaded', poblarMunicipios);
