"""add municipio and referencia to clientes

Revision ID: 741a136799dd
Revises: fc92beb880a6
Create Date: 2026-06-22 15:14:13.871012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '741a136799dd'
down_revision: Union[str, Sequence[str], None] = 'fc92beb880a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('municipio', sa.String(length=150), nullable=True))
    op.add_column('clientes', sa.Column('referencia', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'referencia')
    op.drop_column('clientes', 'municipio')
    # ### end Alembic commands ###
