"""Add SeguimientoVendedor table

Revision ID: e6aa77d11805
Revises: 741a136799dd
Create Date: 2026-06-30 09:05:07.961012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6aa77d11805'
down_revision: Union[str, Sequence[str], None] = '741a136799dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seguimiento_vendedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid_dispositivo', sa.String(length=80), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=False),
    sa.Column('longitud', sa.Float(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('bateria', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vendedor_id'], ['vendedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seguimiento_vendedor_id'), 'seguimiento_vendedor', ['id'], unique=False)
    op.create_index(op.f('ix_seguimiento_vendedor_uuid_dispositivo'), 'seguimiento_vendedor', ['uuid_dispositivo'], unique=True)
    op.create_index(op.f('ix_seguimiento_vendedor_vendedor_id'), 'seguimiento_vendedor', ['vendedor_id'], unique=False)
    op.add_column('abonos', sa.Column('uuid_dispositivo', sa.String(length=80), nullable=True))
    op.create_index(op.f('ix_abonos_uuid_dispositivo'), 'abonos', ['uuid_dispositivo'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_abonos_uuid_dispositivo'), table_name='abonos')
    op.drop_column('abonos', 'uuid_dispositivo')
    op.drop_index(op.f('ix_seguimiento_vendedor_vendedor_id'), table_name='seguimiento_vendedor')
    op.drop_index(op.f('ix_seguimiento_vendedor_uuid_dispositivo'), table_name='seguimiento_vendedor')
    op.drop_index(op.f('ix_seguimiento_vendedor_id'), table_name='seguimiento_vendedor')
    op.drop_table('seguimiento_vendedor')
    # ### end Alembic commands ###
