"""add_pdf_fields_pedido

Revision ID: fc92beb880a6
Revises: 889e71f356ea
Create Date: 2026-06-18 13:56:56.769567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc92beb880a6'
down_revision: Union[str, Sequence[str], None] = '889e71f356ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('clientes_vendedor_id_fkey'), 'clientes', type_='foreignkey')
    op.create_foreign_key(None, 'clientes', 'vendedores', ['vendedor_id'], ['id'])
    op.add_column('detalles_pedido', sa.Column('notas', sa.String(length=250), nullable=True))
    op.add_column('pedidos', sa.Column('numero_pedido', sa.String(length=50), nullable=True))
    op.add_column('pedidos', sa.Column('nit_cedula', sa.String(length=50), nullable=True))
    op.add_column('pedidos', sa.Column('ciudad', sa.String(length=100), nullable=True))
    op.add_column('pedidos', sa.Column('telefono', sa.String(length=50), nullable=True))
    op.add_column('pedidos', sa.Column('correo', sa.String(length=100), nullable=True))
    op.add_column('pedidos', sa.Column('iva', sa.Numeric(precision=12, scale=2), server_default='0.0', nullable=False))
    op.add_column('pedidos', sa.Column('descuento', sa.Numeric(precision=12, scale=2), server_default='0.0', nullable=False))
    op.add_column('pedidos', sa.Column('forma_pago', sa.String(length=50), nullable=True))
    op.add_column('pedidos', sa.Column('condiciones_entrega', sa.String(length=250), nullable=True))
    op.add_column('pedidos', sa.Column('fecha_estimada_entrega', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('pedidos', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_pedidos_numero_pedido'), 'pedidos', ['numero_pedido'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedidos_numero_pedido'), table_name='pedidos')
    op.alter_column('pedidos', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('pedidos', 'fecha_estimada_entrega')
    op.drop_column('pedidos', 'condiciones_entrega')
    op.drop_column('pedidos', 'forma_pago')
    op.drop_column('pedidos', 'descuento')
    op.drop_column('pedidos', 'iva')
    op.drop_column('pedidos', 'correo')
    op.drop_column('pedidos', 'telefono')
    op.drop_column('pedidos', 'ciudad')
    op.drop_column('pedidos', 'nit_cedula')
    op.drop_column('pedidos', 'numero_pedido')
    op.drop_column('detalles_pedido', 'notas')
    op.drop_constraint(None, 'clientes', type_='foreignkey')
    op.create_foreign_key(op.f('clientes_vendedor_id_fkey'), 'clientes', 'vendedores', ['vendedor_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
